// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: procsystem.proto

package procsystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int64                  `protobuf:"varint,3,opt,name=ppid,proto3" json:"ppid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcRequest) Reset() {
	*x = ProcRequest{}
	mi := &file_procsystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcRequest) ProtoMessage() {}

func (x *ProcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_procsystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcRequest.ProtoReflect.Descriptor instead.
func (*ProcRequest) Descriptor() ([]byte, []int) {
	return file_procsystem_proto_rawDescGZIP(), []int{0}
}

func (x *ProcRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProcRequest) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcRequest) GetPpid() int64 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

type ProcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pcb           *Pcb                   `protobuf:"bytes,1,opt,name=pcb,proto3" json:"pcb,omitempty"`
	Pcblist       []*Pcb                 `protobuf:"bytes,2,rep,name=pcblist,proto3" json:"pcblist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcResponse) Reset() {
	*x = ProcResponse{}
	mi := &file_procsystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcResponse) ProtoMessage() {}

func (x *ProcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_procsystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcResponse.ProtoReflect.Descriptor instead.
func (*ProcResponse) Descriptor() ([]byte, []int) {
	return file_procsystem_proto_rawDescGZIP(), []int{1}
}

func (x *ProcResponse) GetPcb() *Pcb {
	if x != nil {
		return x.Pcb
	}
	return nil
}

func (x *ProcResponse) GetPcblist() []*Pcb {
	if x != nil {
		return x.Pcblist
	}
	return nil
}

type Pcb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int64                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int64                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Tgid          int64                  `protobuf:"varint,3,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Createdat     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdat,proto3" json:"createdat,omitempty"`
	Exitedat      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=exitedat,proto3" json:"exitedat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pcb) Reset() {
	*x = Pcb{}
	mi := &file_procsystem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pcb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pcb) ProtoMessage() {}

func (x *Pcb) ProtoReflect() protoreflect.Message {
	mi := &file_procsystem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pcb.ProtoReflect.Descriptor instead.
func (*Pcb) Descriptor() ([]byte, []int) {
	return file_procsystem_proto_rawDescGZIP(), []int{2}
}

func (x *Pcb) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Pcb) GetPpid() int64 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *Pcb) GetTgid() int64 {
	if x != nil {
		return x.Tgid
	}
	return 0
}

func (x *Pcb) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Pcb) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Pcb) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Pcb) GetCreatedat() *timestamppb.Timestamp {
	if x != nil {
		return x.Createdat
	}
	return nil
}

func (x *Pcb) GetExitedat() *timestamppb.Timestamp {
	if x != nil {
		return x.Exitedat
	}
	return nil
}

var File_procsystem_proto protoreflect.FileDescriptor

const file_procsystem_proto_rawDesc = "" +
	"\n" +
	"\x10procsystem.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n" +
	"\vProcRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x03 \x01(\x03R\x04ppid\"L\n" +
	"\fProcResponse\x12\x19\n" +
	"\x03pcb\x18\x01 \x01(\v2\a.pb.PcbR\x03pcb\x12!\n" +
	"\apcblist\x18\x02 \x03(\v2\a.pb.PcbR\apcblist\"\xf5\x01\n" +
	"\x03Pcb\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x03R\x04ppid\x12\x12\n" +
	"\x04tgid\x18\x03 \x01(\x03R\x04tgid\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x128\n" +
	"\tcreatedat\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedat\x126\n" +
	"\bexitedat\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bexitedat2\xd1\x01\n" +
	"\n" +
	"ProcManage\x121\n" +
	"\n" +
	"CreateProc\x12\x0f.pb.ProcRequest\x1a\x10.pb.ProcResponse\"\x00\x12/\n" +
	"\bKillProc\x12\x0f.pb.ProcRequest\x1a\x10.pb.ProcResponse\"\x00\x12/\n" +
	"\bListProc\x12\x0f.pb.ProcRequest\x1a\x10.pb.ProcResponse\"\x00\x12.\n" +
	"\aGetProc\x12\x0f.pb.ProcRequest\x1a\x10.pb.ProcResponse\"\x00B/Z-github.com/BBitQNull/SSHoneyNet/pb/procsystemb\x06proto3"

var (
	file_procsystem_proto_rawDescOnce sync.Once
	file_procsystem_proto_rawDescData []byte
)

func file_procsystem_proto_rawDescGZIP() []byte {
	file_procsystem_proto_rawDescOnce.Do(func() {
		file_procsystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_procsystem_proto_rawDesc), len(file_procsystem_proto_rawDesc)))
	})
	return file_procsystem_proto_rawDescData
}

var file_procsystem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_procsystem_proto_goTypes = []any{
	(*ProcRequest)(nil),           // 0: pb.ProcRequest
	(*ProcResponse)(nil),          // 1: pb.ProcResponse
	(*Pcb)(nil),                   // 2: pb.Pcb
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_procsystem_proto_depIdxs = []int32{
	2, // 0: pb.ProcResponse.pcb:type_name -> pb.Pcb
	2, // 1: pb.ProcResponse.pcblist:type_name -> pb.Pcb
	3, // 2: pb.Pcb.createdat:type_name -> google.protobuf.Timestamp
	3, // 3: pb.Pcb.exitedat:type_name -> google.protobuf.Timestamp
	0, // 4: pb.ProcManage.CreateProc:input_type -> pb.ProcRequest
	0, // 5: pb.ProcManage.KillProc:input_type -> pb.ProcRequest
	0, // 6: pb.ProcManage.ListProc:input_type -> pb.ProcRequest
	0, // 7: pb.ProcManage.GetProc:input_type -> pb.ProcRequest
	1, // 8: pb.ProcManage.CreateProc:output_type -> pb.ProcResponse
	1, // 9: pb.ProcManage.KillProc:output_type -> pb.ProcResponse
	1, // 10: pb.ProcManage.ListProc:output_type -> pb.ProcResponse
	1, // 11: pb.ProcManage.GetProc:output_type -> pb.ProcResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_procsystem_proto_init() }
func file_procsystem_proto_init() {
	if File_procsystem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procsystem_proto_rawDesc), len(file_procsystem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_procsystem_proto_goTypes,
		DependencyIndexes: file_procsystem_proto_depIdxs,
		MessageInfos:      file_procsystem_proto_msgTypes,
	}.Build()
	File_procsystem_proto = out.File
	file_procsystem_proto_goTypes = nil
	file_procsystem_proto_depIdxs = nil
}
