// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: cmdparser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CmdParser_CommandParser_FullMethodName = "/pb.CmdParser/CommandParser"
)

// CmdParserClient is the client API for CmdParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CmdParserClient interface {
	CommandParser(ctx context.Context, in *CmdParserRequest, opts ...grpc.CallOption) (*CmdParserResponse, error)
}

type cmdParserClient struct {
	cc grpc.ClientConnInterface
}

func NewCmdParserClient(cc grpc.ClientConnInterface) CmdParserClient {
	return &cmdParserClient{cc}
}

func (c *cmdParserClient) CommandParser(ctx context.Context, in *CmdParserRequest, opts ...grpc.CallOption) (*CmdParserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CmdParserResponse)
	err := c.cc.Invoke(ctx, CmdParser_CommandParser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CmdParserServer is the server API for CmdParser service.
// All implementations must embed UnimplementedCmdParserServer
// for forward compatibility.
type CmdParserServer interface {
	CommandParser(context.Context, *CmdParserRequest) (*CmdParserResponse, error)
	mustEmbedUnimplementedCmdParserServer()
}

// UnimplementedCmdParserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCmdParserServer struct{}

func (UnimplementedCmdParserServer) CommandParser(context.Context, *CmdParserRequest) (*CmdParserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommandParser not implemented")
}
func (UnimplementedCmdParserServer) mustEmbedUnimplementedCmdParserServer() {}
func (UnimplementedCmdParserServer) testEmbeddedByValue()                   {}

// UnsafeCmdParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CmdParserServer will
// result in compilation errors.
type UnsafeCmdParserServer interface {
	mustEmbedUnimplementedCmdParserServer()
}

func RegisterCmdParserServer(s grpc.ServiceRegistrar, srv CmdParserServer) {
	// If the following call pancis, it indicates UnimplementedCmdParserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CmdParser_ServiceDesc, srv)
}

func _CmdParser_CommandParser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmdParserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdParserServer).CommandParser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CmdParser_CommandParser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdParserServer).CommandParser(ctx, req.(*CmdParserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CmdParser_ServiceDesc is the grpc.ServiceDesc for CmdParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CmdParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CmdParser",
	HandlerType: (*CmdParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommandParser",
			Handler:    _CmdParser_CommandParser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdparser.proto",
}
