// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: dispatcher.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CmdEcho_Dispatcher_FullMethodName = "/pb.CmdEcho/Dispatcher"
)

// CmdEchoClient is the client API for CmdEcho service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CmdEchoClient interface {
	Dispatcher(ctx context.Context, in *DispatcherRequest, opts ...grpc.CallOption) (*DispatcherResponse, error)
}

type cmdEchoClient struct {
	cc grpc.ClientConnInterface
}

func NewCmdEchoClient(cc grpc.ClientConnInterface) CmdEchoClient {
	return &cmdEchoClient{cc}
}

func (c *cmdEchoClient) Dispatcher(ctx context.Context, in *DispatcherRequest, opts ...grpc.CallOption) (*DispatcherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatcherResponse)
	err := c.cc.Invoke(ctx, CmdEcho_Dispatcher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CmdEchoServer is the server API for CmdEcho service.
// All implementations must embed UnimplementedCmdEchoServer
// for forward compatibility.
type CmdEchoServer interface {
	Dispatcher(context.Context, *DispatcherRequest) (*DispatcherResponse, error)
	mustEmbedUnimplementedCmdEchoServer()
}

// UnimplementedCmdEchoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCmdEchoServer struct{}

func (UnimplementedCmdEchoServer) Dispatcher(context.Context, *DispatcherRequest) (*DispatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatcher not implemented")
}
func (UnimplementedCmdEchoServer) mustEmbedUnimplementedCmdEchoServer() {}
func (UnimplementedCmdEchoServer) testEmbeddedByValue()                 {}

// UnsafeCmdEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CmdEchoServer will
// result in compilation errors.
type UnsafeCmdEchoServer interface {
	mustEmbedUnimplementedCmdEchoServer()
}

func RegisterCmdEchoServer(s grpc.ServiceRegistrar, srv CmdEchoServer) {
	// If the following call pancis, it indicates UnimplementedCmdEchoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CmdEcho_ServiceDesc, srv)
}

func _CmdEcho_Dispatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdEchoServer).Dispatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CmdEcho_Dispatcher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdEchoServer).Dispatcher(ctx, req.(*DispatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CmdEcho_ServiceDesc is the grpc.ServiceDesc for CmdEcho service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CmdEcho_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CmdEcho",
	HandlerType: (*CmdEchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatcher",
			Handler:    _CmdEcho_Dispatcher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dispatcher.proto",
}
