// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: sshd.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EchoCmd_EchoCommand_FullMethodName = "/pb.EchoCmd/EchoCommand"
)

// EchoCmdClient is the client API for EchoCmd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoCmdClient interface {
	EchoCommand(ctx context.Context, in *EchoCmdRequest, opts ...grpc.CallOption) (*EchoCmdResponse, error)
}

type echoCmdClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoCmdClient(cc grpc.ClientConnInterface) EchoCmdClient {
	return &echoCmdClient{cc}
}

func (c *echoCmdClient) EchoCommand(ctx context.Context, in *EchoCmdRequest, opts ...grpc.CallOption) (*EchoCmdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoCmdResponse)
	err := c.cc.Invoke(ctx, EchoCmd_EchoCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoCmdServer is the server API for EchoCmd service.
// All implementations must embed UnimplementedEchoCmdServer
// for forward compatibility.
type EchoCmdServer interface {
	EchoCommand(context.Context, *EchoCmdRequest) (*EchoCmdResponse, error)
	mustEmbedUnimplementedEchoCmdServer()
}

// UnimplementedEchoCmdServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoCmdServer struct{}

func (UnimplementedEchoCmdServer) EchoCommand(context.Context, *EchoCmdRequest) (*EchoCmdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoCommand not implemented")
}
func (UnimplementedEchoCmdServer) mustEmbedUnimplementedEchoCmdServer() {}
func (UnimplementedEchoCmdServer) testEmbeddedByValue()                 {}

// UnsafeEchoCmdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoCmdServer will
// result in compilation errors.
type UnsafeEchoCmdServer interface {
	mustEmbedUnimplementedEchoCmdServer()
}

func RegisterEchoCmdServer(s grpc.ServiceRegistrar, srv EchoCmdServer) {
	// If the following call pancis, it indicates UnimplementedEchoCmdServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EchoCmd_ServiceDesc, srv)
}

func _EchoCmd_EchoCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoCmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoCmdServer).EchoCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoCmd_EchoCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoCmdServer).EchoCommand(ctx, req.(*EchoCmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EchoCmd_ServiceDesc is the grpc.ServiceDesc for EchoCmd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoCmd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EchoCmd",
	HandlerType: (*EchoCmdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EchoCommand",
			Handler:    _EchoCmd_EchoCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sshd.proto",
}
