// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sshd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Exitcode      uint32                 `protobuf:"varint,2,opt,name=exitcode,proto3" json:"exitcode,omitempty"`
	Errmsg        string                 `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Log           string                 `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdResult) Reset() {
	*x = CmdResult{}
	mi := &file_sshd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdResult) ProtoMessage() {}

func (x *CmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_sshd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdResult.ProtoReflect.Descriptor instead.
func (*CmdResult) Descriptor() ([]byte, []int) {
	return file_sshd_proto_rawDescGZIP(), []int{0}
}

func (x *CmdResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CmdResult) GetExitcode() uint32 {
	if x != nil {
		return x.Exitcode
	}
	return 0
}

func (x *CmdResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *CmdResult) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type EchoCmdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *CmdResult             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoCmdRequest) Reset() {
	*x = EchoCmdRequest{}
	mi := &file_sshd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoCmdRequest) ProtoMessage() {}

func (x *EchoCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sshd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoCmdRequest.ProtoReflect.Descriptor instead.
func (*EchoCmdRequest) Descriptor() ([]byte, []int) {
	return file_sshd_proto_rawDescGZIP(), []int{1}
}

func (x *EchoCmdRequest) GetResult() *CmdResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type EchoCmdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iserr         bool                   `protobuf:"varint,1,opt,name=iserr,proto3" json:"iserr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoCmdResponse) Reset() {
	*x = EchoCmdResponse{}
	mi := &file_sshd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoCmdResponse) ProtoMessage() {}

func (x *EchoCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sshd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoCmdResponse.ProtoReflect.Descriptor instead.
func (*EchoCmdResponse) Descriptor() ([]byte, []int) {
	return file_sshd_proto_rawDescGZIP(), []int{2}
}

func (x *EchoCmdResponse) GetIserr() bool {
	if x != nil {
		return x.Iserr
	}
	return false
}

var File_sshd_proto protoreflect.FileDescriptor

const file_sshd_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sshd.proto\x12\x02pb\"i\n" +
	"\tCmdResult\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1a\n" +
	"\bexitcode\x18\x02 \x01(\rR\bexitcode\x12\x16\n" +
	"\x06errmsg\x18\x03 \x01(\tR\x06errmsg\x12\x10\n" +
	"\x03log\x18\x04 \x01(\tR\x03log\"7\n" +
	"\x0eEchoCmdRequest\x12%\n" +
	"\x06result\x18\x01 \x01(\v2\r.pb.CmdResultR\x06result\"'\n" +
	"\x0fEchoCmdResponse\x12\x14\n" +
	"\x05iserr\x18\x01 \x01(\bR\x05iserr2C\n" +
	"\aEchoCmd\x128\n" +
	"\vEchoCommand\x12\x12.pb.EchoCmdRequest\x1a\x13.pb.EchoCmdResponse\"\x00B\x0fZ\rSSHoneyNet/pbb\x06proto3"

var (
	file_sshd_proto_rawDescOnce sync.Once
	file_sshd_proto_rawDescData []byte
)

func file_sshd_proto_rawDescGZIP() []byte {
	file_sshd_proto_rawDescOnce.Do(func() {
		file_sshd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sshd_proto_rawDesc), len(file_sshd_proto_rawDesc)))
	})
	return file_sshd_proto_rawDescData
}

var file_sshd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sshd_proto_goTypes = []any{
	(*CmdResult)(nil),       // 0: pb.CmdResult
	(*EchoCmdRequest)(nil),  // 1: pb.EchoCmdRequest
	(*EchoCmdResponse)(nil), // 2: pb.EchoCmdResponse
}
var file_sshd_proto_depIdxs = []int32{
	0, // 0: pb.EchoCmdRequest.result:type_name -> pb.CmdResult
	1, // 1: pb.EchoCmd.EchoCommand:input_type -> pb.EchoCmdRequest
	2, // 2: pb.EchoCmd.EchoCommand:output_type -> pb.EchoCmdResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sshd_proto_init() }
func file_sshd_proto_init() {
	if File_sshd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sshd_proto_rawDesc), len(file_sshd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sshd_proto_goTypes,
		DependencyIndexes: file_sshd_proto_depIdxs,
		MessageInfos:      file_sshd_proto_msgTypes,
	}.Build()
	File_sshd_proto = out.File
	file_sshd_proto_goTypes = nil
	file_sshd_proto_depIdxs = nil
}
